Work Project 3.6/config/routes.rb
Rails.application.routes.draw do
  get 'admin_control/admin_panel'
  get 'admin_control/admin_panel_create'
  get 'admin_control/admin_panel_delete'
  get 'admin_control/admin_panel_update'
  get 'admin_control/create_user'
  get 'admin_control/delete_user'
  get 'admin_control/edit_user'
  root 'candidate_details#index'
  resources :candidate_details
  devise_for :users
  get "Admin_Panel", to: "admin_control#admin_panel", as:"panel"
  get "Admin_Panel_Create", to:"admin_control#admin_panel_create", as:"panel_create"
  post "Admin_Panel", to: "admin_page#admin_panel"
  get "Admin_Panel_Edit", to: "admin_control#admin_panel_update",as: "panel_edit"
  get "Admin_Panel_Delete", to: "admin_control#admin_panel_delete",as: "panel_delete"
  post "Create_User",to: "admin_control#create_user",as:"create_user"
  post "Edit_User", to:"admin_control#edit_user",as:"edit_user"
  post "Delete_User", to:"admin_control#delete_user",as:"delete_user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Work Project 3.6/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Work Project 3.6/app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord
  validates :s_no, presence: {message:"S.No. must specified"},uniqueness: {message:"S.No. already exist."}
  validates :src_reg, presence:true, format:{with: /\AR/,message: "Please enter Source of Regeistration in following format -> N/state abbrivation."}
  validates :src_reg, length:{is: 4,message:"Please enter state abbrivation correctely (only 2 letters of state abbrivation."}
  validates :reg_no,presence: true
  validate :match_regno
  validates :name, presence:{message:"Name must specified."}
  validates :gender, presence:{message:"Gender must specified."}
  validates :age, presence: {message:"Age must specified."}
  validates :email, presence:{message:"Email is required."}, uniqueness: {message:"Email is already exist."},format:{with:/@/,message:"Email must contain @."}
  validates :contact_no, presence:{message:"Contact Number is required."},uniqueness: {message:"Contact Number is already exist."},length: {is: 10,message:"Contact Numbers must be 10 digits."}
  validate :check_remark
  validate :status_now
  def match_regno
    unless reg_no=="NZ/"+src_reg+"/"+s_no.to_s
      errors.add(:reg_no,"Registration Number is incorrect. It must be in following pattern NZ/Source of Registration/S.No.")
    end
  end
  def check_remark
    unless (1..10)===remarks_mobility
      errors.add(:remarks_mobility,"Remark_mobility must be between the range 1 to 10.")
    end
  end
  def status_now
    unless ["pending", "joined", "joining", "not interested", "study", "not responding"].include?status
      errors.add(:status,"Status must be one of following -> pending, joined, joining, not interested, study, not responding.")
    end
  end

end

Work Project 3.6/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.create_new_user(email, password)
    user = User.new(:email => email, :password => password )
    user.save
  end
  def self.edit_user(prev_email,new_email,password)
    user=User.find_by_email(prev_email)
    user.update(:email => new_email, :password => password)
    user.save
  end
  def self.delete_user(email)
    user=User.find_by_email(email)
    user.destroy
  end
end

Work Project 3.6/app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: [:new]

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Work Project 3.6/app/controllers/admin_control_controller.rb
class AdminControlController < ApplicationController
  before_action :isAdmin
  def isAdmin
    unless current_user&&current_user.admin
      redirect_to candidate_details_path,notice: "You are not the Admin"
    end
  end
  def admin_panel
    @all_email=User.all
  end
  def admin_panel_create
    unless params[:password]==params[:password_confirmation]
      render "admin_panel", notice: "Password must match"
    end
  end
  def create_user
    User.create_new_user(params[:email],params[:password])
    redirect_to panel_path
  end
  def edit_user
    User.edit_user(params[:prev_email],params[:email],params[:password])
    redirect_to panel_path
  end
  def delete_user
    User.delete_user(params[:email])
    redirect_to panel_path
  end
end

Work Project 3.6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Work Project 3.6/app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]

  def index
    @candidate_details = CandidateDetail.all
  end
  def show
  end
  def new
    @candidate_detail = CandidateDetail.new
  end
  def edit
  end
  def create
    @candidate_detail = CandidateDetail.new(candidate_detail_params)
    respond_to do |format|
      if @candidate_detail.save
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        format.html { redirect_to @candidate_detail, notice: 'Candidate details was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate details was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end
    def candidate_detail_params
      params.require(:candidate_detail).permit(:s_no, :src_reg, :zone, :DOR, :reg_no, :name, :gender, :age, :address, :branch, :email, :contact_no, :state, :qualification, :specialization, :experience, :remarks_mobility, :DOC, :status)
    end
end

Work Project 3.6/app/helpers/admin_control_helper.rb
module AdminControlHelper
end

Work Project 3.6/app/helpers/application_helper.rb
module ApplicationHelper
end

Work Project 3.6/app/helpers/candidate_details_helper.rb
module CandidateDetailsHelper
end

Work Project 3.6/app/views/admin_control/admin_panel.html.erb
<p id="notice"><%= notice %></p>
<h1>Admin Pages</h1>
<div class="table-responsive table-bordered">
  <table class="table">
    <thead>
    <tr>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @all_email.each do |mail| %>
      <tr>
        <td><%= mail.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="text-center">
  <br>
<%= link_to 'Create User', panel_create_path, class:"btn btn-default" %>
<%= link_to 'Edit User', panel_edit_path,class:"btn btn-info" %>
<%= link_to 'Delete User',panel_delete_path,class:"btn btn-warning" %><br><br>
<%= link_to 'Back',candidate_details_path,class: "btn btn-default" %>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_create.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Create User</h1>
    <%= form_tag create_user_path do |user| %>
      <div class="field">
        <%= label_tag :email ,"Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :password,"Password (6 characters minimum)" %>
        <%= password_field_tag :password%>
      </div>
      <div class="field">
        <%=label_tag :password_confirmation,"Password Confirmation" %>
        <%=password_field_tag :Password_confirmation %>
      </div>
      <div class="actions">
        <%= submit_tag "Create User" %>
      </div>
    <% end %>
  </div>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_delete.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Delete User</h1>
    <%= form_tag delete_user_path do |user| %>
      <div class="field">
        <%= label_tag :email ,"Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="actions">
        <%= submit_tag "Delete User" %>
      </div>
    <% end %>
  </div>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_update.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Update User</h1>
    <%= form_tag edit_user_path do |user| %>
      <div class="field">
        <%=label_tag :prev_email,"Previous Email" %>
        <%=email_field_tag :prev_email %>
      </div>
      <div class="field">
        <%= label_tag :email ,"New Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :password,"Password (6 characters minimum)" %>
        <%= password_field_tag :password%>
      </div>
      <div class="field">
        <%=label_tag :password_confirmation,"Password Confirmation" %>
        <%=password_field_tag :Password_confirmation %>
      </div>
      <div class="actions">
        <%= submit_tag "Edit User" %>
      </div>
    <% end %>
  </div>
</div>

Work Project 3.6/app/views/candidate_details/_form.html.erb
<div class="main-agileinfo">
<div class="agileits-top">
<%= form_with(model: candidate_detail, local: true) do |form| %>
  <% if candidate_detail.errors.any? %>
    <div class="alert alert-warning" >
      <h2><%= pluralize(candidate_detail.errors.count, "error") %> prohibited this candidate_detail from being saved:</h2>
      <ul>
      <% candidate_detail.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :s_no ,"S.No."%><br>
    <%= form.number_field :s_no %>
  </div>
  <div class="field">
    <%= form.label :src_reg,"Source of registration" %>
    <%= form.text_field :src_reg %>
  </div>
  <div class="field">
    <%= form.label :zone ,"Zone"%>
    <%= form.text_field :zone %>
  </div>
  <div class="field">
    <%= form.label :DOR ,"Date of registration"%><br>
    <%= form.date_select :DOR %>
  </div>
  <div class="field">
    <%= form.label :reg_no ,"Registration number"%>
    <%= form.text_field :reg_no %>
  </div>
  <div class="field">
    <%= form.label :name ,"Name"%>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :gender,"Gender" %>
    <%= form.text_field :gender %>
  </div>
  <div class="field">
    <%= form.label :age ,"Age"%><br>
    <%= form.number_field :age %>
  </div>
  <div class="field">
    <%= form.label :address ,"Address"%><br>
    <%= form.text_area :address %>
  </div>
  <div class="field">
    <%= form.label :branch,"Branch" %>
    <%= form.text_field :branch %>
  </div>
  <div class="field">
    <%= form.label :email,"Email" %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :contact_no,"Contact number" %><br>
    <%= form.number_field :contact_no %>
  </div>
  <div class="field">
    <%= form.label :state,"State" %>
    <%= form.text_field :state %>
  </div>
  <div class="field">
    <%= form.label :qualification,"Qualification" %>
    <%= form.text_field :qualification %>
  </div>
  <div class="field">
    <%= form.label :specialization ,"Specialization"%>
    <%= form.text_field :specialization %>
  </div>
  <div class="field">
    <%= form.label :experience,"Experience" %>
    <%= form.text_field :experience %>
  </div>
  <div class="field">
    <%= form.label :remarks_mobility ,"Remarks Mobility"%><br>
    <%= form.number_field :remarks_mobility %>
  </div>
  <div class="field">
    <%= form.label :DOC ,"Date of closure"%><br>
    <%= form.date_select :DOC%>
  </div>
  <div class="field">
    <%= form.label :status,"Status" %>
    <%= form.text_field :status %>
  </div>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>
</div>

Work Project 3.6/app/views/candidate_details/edit.html.erb
<br><br><br>
<h1>Editing Candidate Detail</h1>
<%= render 'form', candidate_detail: @candidate_detail %>
<div class="text-center">
<%= link_to 'Show', @candidate_detail,class:"btn btn-default" %> |
<%= link_to 'Back', candidate_details_path ,class:"btn btn-default"%>
</div>

Work Project 3.6/app/views/candidate_details/index.html.erb
<h1>Candidate Details</h1>
<div class="table-responsive table-bordered">
<table class="table">
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Registration Number</th>
      <th>Name</th>
      <th>Branch</th>
      <th>Email</th>
      <th>Contact Number</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @candidate_details.each do |candidate_detail| %>
      <tr>
        <td><%= candidate_detail.s_no %></td>
        <td><%= candidate_detail.reg_no %></td>
        <td><%= candidate_detail.name %></td>
        <td><%= candidate_detail.branch %></td>
        <td><%= candidate_detail.email %></td>
        <td><%= candidate_detail.contact_no %></td>
        <td><%= candidate_detail.status %></td>
        <td><%= link_to 'Read', candidate_detail,class:"btn btn-default" %></td>
        <td><%= link_to 'Update', edit_candidate_detail_path(candidate_detail),class:"btn btn-info" %></td>
        <td><%= link_to 'Delete', candidate_detail, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="text-center">
<%= link_to 'Create', new_candidate_detail_path,class:"btn btn-default"%> |
<%= link_to 'Filter',candidate_details_path,class:"btn btn-default"%>
  <%if current_user && current_user.admin %>
    | <%=link_to "Admin Panel", panel_path,class: "btn btn-default" %>
  <%end %>
</div>

Work Project 3.6/app/views/candidate_details/new.html.erb
<br><br><br>
<h1>New Candidate Detail</h1>
<%= render 'form', candidate_detail: @candidate_detail %>
<div class="text-center">
  <%= link_to 'Back', candidate_details_path,class:"btn btn-default" %>
</div>

Work Project 3.6/app/views/candidate_details/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>S no:</strong>
  <%= @candidate_detail.s_no %>
</p>
<p>
  <strong>Src reg:</strong>
  <%= @candidate_detail.src_reg %>
</p>
<p>
  <strong>Zone:</strong>
  <%= @candidate_detail.zone %>
</p>
<p>
  <strong>Dor:</strong>
  <%= @candidate_detail.DOR %>
</p>
<p>
  <strong>Reg no:</strong>
  <%= @candidate_detail.reg_no %>
</p>
<p>
  <strong>Name:</strong>
  <%= @candidate_detail.name %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @candidate_detail.gender %>
</p>
<p>
  <strong>Age:</strong>
  <%= @candidate_detail.age %>
</p>
<p>
  <strong>Address:</strong>
  <%= @candidate_detail.address %>
</p>
<p>
  <strong>Branch:</strong>
  <%= @candidate_detail.branch %>
</p>
<p>
  <strong>Email:</strong>
  <%= @candidate_detail.email %>
</p>
<p>
  <strong>Contact no:</strong>
  <%= @candidate_detail.contact_no %>
</p>
<p>
  <strong>State:</strong>
  <%= @candidate_detail.state %>
</p>
<p>
  <strong>Qualification:</strong>
  <%= @candidate_detail.qualification %>
</p>
<p>
  <strong>Specialization:</strong>
  <%= @candidate_detail.specialization %>
</p>
<p>
  <strong>Experience:</strong>
  <%= @candidate_detail.experience %>
</p>
<p>
  <strong>Remarks mobility:</strong>
  <%= @candidate_detail.remarks_mobility %>
</p>
<p>
  <strong>Doc:</strong>
  <%= @candidate_detail.DOC %>
</p>
<p>
  <strong>Status:</strong>
  <%= @candidate_detail.status %>
</p>
<div class="text-center">
<%= link_to 'Edit', edit_candidate_detail_path(@candidate_detail),class:"btn btn-default" %> |
<%= link_to 'Back', candidate_details_path ,class:"btn btn-default"%>
</div>

Work Project 3.6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkProject34</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="main-w3layouts wrapper">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% end %>
  </p>
    <%= yield %>
		</div>
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
  </body>
</html>