config/routes.rb
Rails.application.routes.draw do
  root 'candidate_details#index'
  resources :candidate_details

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord
validates :name, presence:true
  validates :src_reg, presence:true
  validates :gender, presence:true
  validates :age, presence:true
  validates :email, presence:true
  validates :contact_no, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]

  # GET /candidate_details
  # GET /candidate_details.json
  def index
    @candidate_details = CandidateDetail.all
  end

  # GET /candidate_details/1
  # GET /candidate_details/1.json
  def show
  end

  # GET /candidate_details/new
  def new
    @candidate_detail = CandidateDetail.new
  end

  # GET /candidate_details/1/edit
  def edit
  end

  # POST /candidate_details
  # POST /candidate_details.json
  def create
    @candidate_detail = CandidateDetail.new(candidate_detail_params)

    respond_to do |format|
      if @candidate_detail.save
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate_details/1
  # PATCH/PUT /candidate_details/1.json
  def update
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_details/1
  # DELETE /candidate_details/1.json
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_detail_params
      params.require(:candidate_detail).permit(:s_no, :src_reg, :zone, :DOR, :reg_no, :name, :gender, :age, :address, :branch, :email, :contact_no, :state, :qualification, :specialization, :experience, :remarks_mobility, :DOC, :status)
    end
end

app/views/candidate_details/_form.html.erb
<div class="main-agileinfo">
<div class="agileits-top">
				
<%= form_with(model: candidate_detail, local: true) do |form| %>
  <% if candidate_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate_detail.errors.count, "error") %> prohibited this candidate_detail from being saved:</h2>

      <ul>
      <% candidate_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :s_no %>
    <%= form.number_field :s_no %>
  </div>

  <div class="field">
    <%= form.label :src_reg %>
    <%= form.text_field :src_reg %>
  </div>

  <div class="field">
    <%= form.label :zone %>
    <%= form.text_field :zone %>
  </div>

  <div class="field">
    <%= form.label :DOR %>
    <%= form.date_select :DOR %>
  </div>

  <div class="field">
    <%= form.label :reg_no %>
    <%= form.text_field :reg_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contact_no %>
    <%= form.number_field :contact_no %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification %>
  </div>

  <div class="field">
    <%= form.label :specialization %>
    <%= form.text_field :specialization %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.label :remarks_mobility %>
    <%= form.number_field :remarks_mobility %>
  </div>

  <div class="field">
    <%= form.label :DOC %>
    <%= form.date_select :DOC %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/candidate_details/edit.html.erb
<br><br><br>
<h1>Editing Candidate Detail</h1>

<%= render 'form', candidate_detail: @candidate_detail %>

<%= link_to 'Show', @candidate_detail %> |
<%= link_to 'Back', candidate_details_path %>

app/views/candidate_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidate Details</h1>
<div class="table-responsive table-bordered">
<table class="table">
  <thead>
    <tr>
      <th>S no</th>
      <th>Reg no</th>
      <th>Name</th>
      <th>Branch</th>
      <th>Email</th>
      <th>Contact no</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidate_details.each do |candidate_detail| %>
      <tr>
        <td><%= candidate_detail.s_no %></td>
        <td><%= candidate_detail.reg_no %></td>
        <td><%= candidate_detail.name %></td>
        <td><%= candidate_detail.branch %></td>
        <td><%= candidate_detail.email %></td>
        <td><%= candidate_detail.contact_no %></td>
        <td><%= candidate_detail.status %></td>
        <td><%= link_to 'Read', candidate_detail %></td>
        <td><%= link_to 'Update', edit_candidate_detail_path(candidate_detail) %></td>
        <td><%= link_to 'Delete', candidate_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Create', new_candidate_detail_path %>

app/views/candidate_details/new.html.erb
<br><br><br>
<h1>New Candidate Detail</h1>

<%= render 'form', candidate_detail: @candidate_detail %>
<%= link_to 'Back', candidate_details_path %>

app/views/candidate_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S no:</strong>
  <%= @candidate_detail.s_no %>
</p>

<p>
  <strong>Src reg:</strong>
  <%= @candidate_detail.src_reg %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @candidate_detail.zone %>
</p>

<p>
  <strong>Dor:</strong>
  <%= @candidate_detail.DOR %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @candidate_detail.reg_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @candidate_detail.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @candidate_detail.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @candidate_detail.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @candidate_detail.address %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @candidate_detail.branch %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate_detail.email %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @candidate_detail.contact_no %>
</p>

<p>
  <strong>State:</strong>
  <%= @candidate_detail.state %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @candidate_detail.qualification %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @candidate_detail.specialization %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @candidate_detail.experience %>
</p>

<p>
  <strong>Remarks mobility:</strong>
  <%= @candidate_detail.remarks_mobility %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @candidate_detail.DOC %>
</p>

<p>
  <strong>Status:</strong>
  <%= @candidate_detail.status %>
</p>

<%= link_to 'Edit', edit_candidate_detail_path(@candidate_detail) %> |
<%= link_to 'Back', candidate_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkProject34</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="main-w3layouts wrapper">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
    <%= yield %>
		</div>
		
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
  </body>
</html>